workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - flutter clean
      - rm pubspec.lock || true
      - rm -rf .dart_tool || true
      - flutter pub get
      - flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
