name: noite_aqui
description: Projeto Noite Aqui com estrutura válida
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true